# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Christian Ngubana
email: christian1.raymond@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Built with Jekyll
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://christiangubana.github.io" # the base hostname & protocol for your site
twitter_username: christiangubana
github_username:  christiangubana
linkedin_username: christiangubana

# Build settings
markdown: kramdown

# Disqus comments
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      comments: true